name: Build Docker Image and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read projectId from config
        run: |
          CONFIG_FILE=".vizier/config.json"
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "$CONFIG_FILE not found. Run vizier init to generate it." >&2
            exit 1
          fi
          PROJECT_ID=$(jq -r '.projectId // empty' "$CONFIG_FILE")
          if [ -z "$PROJECT_ID" ]; then
            echo "projectId missing from $CONFIG_FILE" >&2
            cat "$CONFIG_FILE"
            exit 1
          fi
          echo "PROJECT_ID=$PROJECT_ID" >> "$GITHUB_ENV"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create ECR repo if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names "$PROJECT_ID" || \
          aws ecr create-repository --repository-name "$PROJECT_ID"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.PROJECT_ID }}:${{ github.sha }}

      - name: Capture image URL
        id: push-image
        run: |
          echo "image_url=${{ steps.login-ecr.outputs.registry }}/${{ env.PROJECT_ID }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"
