name: Build Docker Image and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read repository/cluster/service from outputs
        run: |
          OUTPUTS_FILE=".vizier/outputs.json"
          if [ ! -f "$OUTPUTS_FILE" ]; then
            echo "$OUTPUTS_FILE not found. Run vizier deploy once to generate it." >&2
            exit 1
          fi
          REPOSITORY_URI=$(jq -r '.repositoryUri // empty' "$OUTPUTS_FILE")
          CLUSTER_NAME=$(jq -r '.clusterName // empty' "$OUTPUTS_FILE")
          SERVICE_NAME=$(jq -r '.serviceName // empty' "$OUTPUTS_FILE")
          if [ -z "$REPOSITORY_URI" ] || [ -z "$CLUSTER_NAME" ] || [ -z "$SERVICE_NAME" ]; then
            echo "repositoryUri, clusterName, or serviceName missing from $OUTPUTS_FILE" >&2
            cat "$OUTPUTS_FILE"
            exit 1
          fi
          {
            echo "REPOSITORY_URI=$REPOSITORY_URI"
            echo "CLUSTER_NAME=$CLUSTER_NAME"
            echo "SERVICE_NAME=$SERVICE_NAME"
          } >> "$GITHUB_ENV"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REPOSITORY_URI }}:latest

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster "$CLUSTER_NAME" \
            --service "$SERVICE_NAME" \
            --force-new-deployment
