name: Sync Assets to S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install project dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build static assets (if defined)
        run: npm run build --if-present

      - name: Read assetDirectory and projectId from config
        run: |
          CONFIG_FILE=".vizier/config.json"
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "$CONFIG_FILE not found. Run vizier init to generate it." >&2
            exit 1
          fi
          ASSET_DIR=$(jq -r '.assetDirectory // empty' "$CONFIG_FILE")
          PROJECT_ID=$(jq -r '.projectId // empty' "$CONFIG_FILE")
          if [ -z "$ASSET_DIR" ]; then
            echo "assetDirectory missing from $CONFIG_FILE" >&2
            cat "$CONFIG_FILE"
            exit 1
          fi
          if [ -z "$PROJECT_ID" ]; then
            echo "projectId missing from $CONFIG_FILE" >&2
            cat "$CONFIG_FILE"
            exit 1
          fi
          if [ ! -d "$ASSET_DIR" ]; then
            echo "Asset directory '$ASSET_DIR' not found. Ensure your build step creates it." >&2
            exit 1
          fi
          {
            echo "ASSET_DIR=$ASSET_DIR"
            echo "PROJECT_ID=$PROJECT_ID"
          } >> "$GITHUB_ENV"

      - name: Read bucketName from outputs
        run: |
          OUTPUTS_FILE=".vizier/outputs.json"
          if [ ! -f "$OUTPUTS_FILE" ]; then
            echo "$OUTPUTS_FILE not found. Run vizier deploy once to generate it." >&2
            exit 1
          fi
          BUCKET_NAME=$(jq -r '.bucketName // empty' "$OUTPUTS_FILE")
          if [ -z "$BUCKET_NAME" ]; then
            echo "bucketName missing from $OUTPUTS_FILE" >&2
            cat "$OUTPUTS_FILE"
            exit 1
          fi
          echo "S3_BUCKET=$BUCKET_NAME" >> "$GITHUB_ENV"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync assets to S3
        run: aws s3 sync "$ASSET_DIR"/ s3://$S3_BUCKET/ --delete

      - name: Invalidate CloudFront cache
        run: |
          DIST_ID=$(aws cloudformation describe-stack-resources \
            --stack-name "$PROJECT_ID" \
            --query "StackResources[?ResourceType=='AWS::CloudFront::Distribution'].PhysicalResourceId" \
            --output text)

          if [ -z "$DIST_ID" ] || [ "$DIST_ID" = "None" ]; then
            echo "No CloudFront distribution found for stack $PROJECT_ID. Skipping invalidation."
            exit 0
          fi

          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"
